DISABLE:
  - COPYPASTE # too many false-positives for the time being
  - EDITORCONFIG # instead usable from super-linter
  - JAVASCRIPT
  - TYPESCRIPT
  - CSS

DISABLE_LINTERS:
  - SPELL_CSPELL

# Override default config files
DOCKERFILE_HADOLINT_CONFIG_FILE: .hadolint.yaml
RUBY_RUBOCOP_CONFIG_FILE: .rubocop.yml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
