extends:
  - stylelint-config-standard
  - stylelint-config-recommended-scss
  - stylelint-config-property-sort-order-smacss

rules:
  # enable prefices
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  property-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true

  # config quotes
  font-family-name-quotes: always-where-recommended
  function-url-quotes: always
  selector-attribute-quotes: always
  string-quotes: single

  # misc
  alpha-value-notation: number

ignoreFiles:
  - "**/*.js"
  - "**/public/**"
