name: Lint

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  azlint:
    name: AZLint
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Debug
        run: |
          echo "branch: $GITHUB_REF_NAME"
      - name: Debug2
        run: |
          pwd
          echo
          ls -lah
          echo
          find .
      # - name: Run AZLint
      #   run: |
      #     azlint
