name: Lint

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  azlint:
    name: AZLint
    runs-on: ubuntu-latest
    container: matejkosiarcik/azlint:0.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Debug
        run: |
          echo "ref: $GITHUB_REF_NAME"

      - name: Run AZLint
        if: github.ref == 'refs/heads/main'
        run: azlint

      - name: Run AZLint
        if: github.ref != 'refs/heads/main'
        run: azlint --only-changed
