name: Update defaults

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 1 * * *"  # daily, 1am
  push:
    branches:
      - master

jobs:
  update-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout defaults
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: defaults
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: matejkosiarcik/web
          path: project
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install --yes --no-install-recommends snapd && \
          sudo snap install yq
      - name: Update defaults
        run: |
          yq read project/.defaults.yml 'files.*' | \
          awk -F ': ' '{printf "defaults/%s project/%s\n", match($2, /[^ ]/) ? $2 : $1, $1}' | \
          xargs -n2 cp -r
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update defaults
          path: project
          assignees: matejkosiarcik
          reviewers: matejkosiarcik
